/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ccx_sub_entry.proto */

#ifndef PROTOBUF_C_ccx_5fsub_5fentry_2eproto__INCLUDED
#define PROTOBUF_C_ccx_5fsub_5fentry_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _PbSubEntry PbSubEntry;


/* --- enums --- */


/* --- messages --- */

struct  _PbSubEntry
{
  ProtobufCMessage base;
  int32_t eos;
  char *stream_name;
  protobuf_c_boolean has_counter;
  int64_t counter;
  protobuf_c_boolean has_start_time;
  int64_t start_time;
  protobuf_c_boolean has_end_time;
  int64_t end_time;
  protobuf_c_boolean has_lines_count;
  int64_t lines_count;
  size_t n_lines;
  char **lines;
};
#define PB_SUB_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pb_sub_entry__descriptor) \
    , 0, NULL, 0,0, 0,0, 0,0, 0,0, 0,NULL }


/* PbSubEntry methods */
void   pb_sub_entry__init
                     (PbSubEntry         *message);
size_t pb_sub_entry__get_packed_size
                     (const PbSubEntry   *message);
size_t pb_sub_entry__pack
                     (const PbSubEntry   *message,
                      uint8_t             *out);
size_t pb_sub_entry__pack_to_buffer
                     (const PbSubEntry   *message,
                      ProtobufCBuffer     *buffer);
PbSubEntry *
       pb_sub_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pb_sub_entry__free_unpacked
                     (PbSubEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PbSubEntry_Closure)
                 (const PbSubEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pb_sub_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ccx_5fsub_5fentry_2eproto__INCLUDED */
