/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ccx_sub_entry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ccx_sub_entry.pb_c.h"
void   pb_sub_entry__init
                     (PbSubEntry         *message)
{
  static PbSubEntry init_value = PB_SUB_ENTRY__INIT;
  *message = init_value;
}
size_t pb_sub_entry__get_packed_size
                     (const PbSubEntry *message)
{
  assert(message->base.descriptor == &pb_sub_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb_sub_entry__pack
                     (const PbSubEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb_sub_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb_sub_entry__pack_to_buffer
                     (const PbSubEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb_sub_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbSubEntry *
       pb_sub_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbSubEntry *)
     protobuf_c_message_unpack (&pb_sub_entry__descriptor,
                                allocator, len, data);
}
void   pb_sub_entry__free_unpacked
                     (PbSubEntry *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb_sub_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pb_sub_entry__field_descriptors[7] =
{
  {
    "eos",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PbSubEntry, eos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream_name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PbSubEntry, stream_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counter",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(PbSubEntry, has_counter),
    offsetof(PbSubEntry, counter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(PbSubEntry, has_start_time),
    offsetof(PbSubEntry, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_time",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(PbSubEntry, has_end_time),
    offsetof(PbSubEntry, end_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lines_count",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(PbSubEntry, has_lines_count),
    offsetof(PbSubEntry, lines_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lines",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(PbSubEntry, n_lines),
    offsetof(PbSubEntry, lines),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb_sub_entry__field_indices_by_name[] = {
  2,   /* field[2] = counter */
  4,   /* field[4] = end_time */
  0,   /* field[0] = eos */
  6,   /* field[6] = lines */
  5,   /* field[5] = lines_count */
  3,   /* field[3] = start_time */
  1,   /* field[1] = stream_name */
};
static const ProtobufCIntRange pb_sub_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor pb_sub_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb_sub_entry",
  "PbSubEntry",
  "PbSubEntry",
  "",
  sizeof(PbSubEntry),
  7,
  pb_sub_entry__field_descriptors,
  pb_sub_entry__field_indices_by_name,
  1,  pb_sub_entry__number_ranges,
  (ProtobufCMessageInit) pb_sub_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
