// Some basic English words, so user-defined doesn't have to
// include the common stuff

pub static mut profane: Vec<String> = Vec::new();
pub static mut capitalization_list: Vec<String> = Vec::new();

pub const CAPITALIZED_BUILTIN: [&str; 29] = [
    "I",
    "I'd",
    "I've",
    "I'd",
    "I'll",
    "January",
    "February",
    "March",
    "April", // May skipped intentionally
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
    "Halloween",
    "United States",
    "Spain",
    "France",
    "Italy",
    "England",
];
pub const PROFANE_BUILTIN: [&str; 25] = [
    "arse",
    "ass",
    "asshole",
    "bastard",
    "bitch",
    "bollocks",
    "child-fucker",
    "crap",
    "cunt",
    "damn",
    "frigger",
    "fuck",
    "goddamn",
    "godsdamn",
    "hell",
    "holy",
    "horseshit",
    "motherfucker",
    "nigga",
    "nigger",
    "prick",
    "shit",
    "shitass",
    "slut",
    "twat",
];
