// Allow C naming style
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// Include C bindings generated by bindgen
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[no_mangle]
pub extern "C" fn process(ctx: *mut lib_cc_decode,
    data: *const ::std::os::raw::c_uchar,
    data_length: ::std::os::raw::c_int,) {
        println!("Hello from rust!!!!!!!!");
        unsafe {
            ccx_dtvcc_process_data(ctx, data, data_length);
        }
}
