FROM alpine:latest

RUN apk add --no-cache --update git curl gcc cmake glew glfw \
  tesseract-ocr-dev leptonica-dev  make pkgconfig \
  zlib-dev libpng-dev libjpeg-turbo-dev openssl-dev freetype-dev libxml2-dev

WORKDIR /root
RUN git clone https://github.com/CCExtractor/ccextractor.git 
RUN apk add bash cargo
RUN export LIB_CLANG_PATH=$(find / -name 'libclang*.so*' 2>/dev/null | grep -v 'No such file' | head -n 1 | xargs dirname)
RUN cd /root/ccextractor/linux && ./pre-build.sh && ./build

RUN cp /root/ccextractor/linux/ccextractor /ccextractor && rm -rf ~/ccextractor

