use crate::decoder_vbi::exit_codes::*;
use crate::decoder_vbi::structs_vbi_decode::*;

// 2 fields skip - fixme(if 0), last one(default/with all zeroes)
pub const VBI_SERVICE_TABLE: [VbiServicePar; 20 - 2] = [
    VbiServicePar {
        id: VBI_SLICED_TELETEXT_A,
        label: c"Teletext System A".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_625_50,
        first: [6, 318],
        last: [22, 335],
        offset: 10500,
        cri_rate: 6203125,
        bit_rate: 6203125,
        cri_frc: 0x00AAAAE7,
        cri_frc_mask: 0xFFFF,
        cri_bits: 18,
        frc_bits: 6,
        payload: 37 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineNum,
    },
    VbiServicePar {
        id: VBI_SLICED_TELETEXT_B_L10_625,
        label: c"Teletext System B 625 Level 1.5".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_625_50,
        first: [7, 320],
        last: [22, 335],
        offset: 10300,
        cri_rate: 6937500,
        bit_rate: 6937500,
        cri_frc: 0x00AAAAE4,
        cri_frc_mask: 0xFFFF,
        cri_bits: 18,
        frc_bits: 6,
        payload: 42 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineNum,
    },
    VbiServicePar {
        id: VBI_SLICED_TELETEXT_B,
        label: c"Teletext System B, 625".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_625_50,
        first: [6, 318],
        last: [22, 335],
        offset: 10300,
        cri_rate: 6937500,
        bit_rate: 6937500,
        cri_frc: 0x00AAAAE4,
        cri_frc_mask: 0xFFFF,
        cri_bits: 18,
        frc_bits: 6,
        payload: 42 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineNum,
    },
    VbiServicePar {
        id: VBI_SLICED_TELETEXT_C_625,
        label: c"Teletext System C 625".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_625_50,
        first: [6, 318],
        last: [22, 335],
        offset: 10480,
        cri_rate: 5734375,
        bit_rate: 5734375,
        cri_frc: 0x00AAAAE7,
        cri_frc_mask: 0xFFFF,
        cri_bits: 18,
        frc_bits: 6,
        payload: 33 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineNum,
    },
    VbiServicePar {
        id: VBI_SLICED_TELETEXT_D_625,
        label: c"Teletext System D 625".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_625_50,
        first: [6, 318],
        last: [22, 335],
        offset: 10500,
        cri_rate: 5642787,
        bit_rate: 5642787,
        cri_frc: 0x00AAAAE5,
        cri_frc_mask: 0xFFFF,
        cri_bits: 18,
        frc_bits: 6,
        payload: 34 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineNum,
    },
    VbiServicePar {
        id: VBI_SLICED_VPS,
        label: c"Video Program System".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_PAL_BG,
        first: [16, 0],
        last: [16, 0],
        offset: 12500,
        cri_rate: 5000000,
        bit_rate: 2500000,
        cri_frc: 0xAAAA8A99,
        cri_frc_mask: 0xFFFFFF,
        cri_bits: 32,
        frc_bits: 0,
        payload: 13 * 8,
        modulation: VbiModulation::BiphaseMsb,
        flags: VbiServiceParFlag::FieldNum,
    },
    VbiServicePar {
        id: VBI_SLICED_VPS_F2,
        label: c"Pseudo-VPS on field 2".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_PAL_BG,
        first: [0, 329],
        last: [0, 329],
        offset: 12500,
        cri_rate: 5000000,
        bit_rate: 2500000,
        cri_frc: 0xAAAA8A99,
        cri_frc_mask: 0xFFFFFF,
        cri_bits: 32,
        frc_bits: 0,
        payload: 13 * 8,
        modulation: VbiModulation::BiphaseMsb,
        flags: VbiServiceParFlag::FieldNum,
    },
    VbiServicePar {
        id: VBI_SLICED_WSS_625,
        label: c"Wide Screen Signalling 625".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_625_50,
        first: [23, 0],
        last: [23, 0],
        offset: 11000,
        cri_rate: 5000000,
        bit_rate: 833333,
        cri_frc: 0x8E3C783E,
        cri_frc_mask: 0x2499339C,
        cri_bits: 32,
        frc_bits: 0,
        payload: 14,
        modulation: VbiModulation::BiphaseLsb,
        flags: VbiServiceParFlag::LineAndField,
    },
    VbiServicePar {
        id: VBI_SLICED_CAPTION_625_F1,
        label: c"Closed Caption 625, field 1".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_625_50,
        first: [22, 0],
        last: [22, 0],
        offset: 10500,
        cri_rate: 1000000,
        bit_rate: 500000,
        cri_frc: 0x00005551,
        cri_frc_mask: 0x7FF,
        cri_bits: 14,
        frc_bits: 2,
        payload: 2 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::FieldNum,
    },
    VbiServicePar {
        id: VBI_SLICED_CAPTION_625_F2,
        label: c"Closed Caption 625, field 2".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_625_50,
        first: [0, 335],
        last: [0, 335],
        offset: 10500,
        cri_rate: 1000000,
        bit_rate: 500000,
        cri_frc: 0x00005551,
        cri_frc_mask: 0x7FF,
        cri_bits: 14,
        frc_bits: 2,
        payload: 2 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::FieldNum,
    },
    VbiServicePar {
        id: VBI_SLICED_VBI_625,
        label: c"VBI 625".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_625_50,
        first: [6, 318],
        last: [22, 335],
        offset: 10000,
        cri_rate: 1510000,
        bit_rate: 1510000,
        cri_frc: 0,
        cri_frc_mask: 0,
        cri_bits: 0,
        frc_bits: 0,
        payload: 10 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineNum,
    },
    VbiServicePar {
        id: VBI_SLICED_TELETEXT_B_525,
        label: c"Teletext System B 525".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_525_60,
        first: [10, 272],
        last: [21, 284],
        offset: 10500,
        cri_rate: 5727272,
        bit_rate: 5727272,
        cri_frc: 0x00AAAAE4,
        cri_frc_mask: 0xFFFF,
        cri_bits: 18,
        frc_bits: 6,
        payload: 34 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineNum,
    },
    VbiServicePar {
        id: VBI_SLICED_TELETEXT_C_525,
        label: c"Teletext System C 525".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_525_60,
        first: [10, 272],
        last: [21, 284],
        offset: 10480,
        cri_rate: 5727272,
        bit_rate: 5727272,
        cri_frc: 0x00AAAAE7,
        cri_frc_mask: 0xFFFF,
        cri_bits: 18,
        frc_bits: 6,
        payload: 33 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineNum,
    },
    VbiServicePar {
        id: VBI_SLICED_TELETEXT_D_525,
        label: c"Teletext System D 525".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_525_60,
        first: [10, 272],
        last: [21, 284],
        offset: 9780,
        cri_rate: 5727272,
        bit_rate: 5727272,
        cri_frc: 0x00AAAAE5,
        cri_frc_mask: 0xFFFF,
        cri_bits: 18,
        frc_bits: 6,
        payload: 34 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineNum,
    },
    VbiServicePar {
        id: VBI_SLICED_CAPTION_525_F1,
        label: c"Closed Caption 525, field 1".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_525_60,
        first: [21, 0],
        last: [21, 0],
        offset: 10500,
        cri_rate: 1006976,
        bit_rate: 503488,
        cri_frc: 0x03,
        cri_frc_mask: 0x0F,
        cri_bits: 4,
        frc_bits: 0,
        payload: 2 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineAndField,
    },
    VbiServicePar {
        id: VBI_SLICED_CAPTION_525_F2,
        label: c"Closed Caption 525, field 2".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_525_60,
        first: [0, 284],
        last: [0, 284],
        offset: 10500,
        cri_rate: 1006976,
        bit_rate: 503488,
        cri_frc: 0x03,
        cri_frc_mask: 0x0F,
        cri_bits: 4,
        frc_bits: 0,
        payload: 2 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineAndField,
    },
    VbiServicePar {
        id: VBI_SLICED_2XCAPTION_525,
        label: c"2xCaption 525".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_525_60,
        first: [10, 0],
        last: [21, 0],
        offset: 10500,
        cri_rate: 1006976,
        bit_rate: 1006976,
        cri_frc: 0x000554ED,
        cri_frc_mask: 0xFFFF,
        cri_bits: 12,
        frc_bits: 8,
        payload: 4 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::FieldNum,
    },
    VbiServicePar {
        id: VBI_SLICED_VBI_525,
        label: c"VBI 525".as_ptr(),
        videostd_set: VBI_VIDEOSTD_SET_525_60,
        first: [10, 272],
        last: [21, 284],
        offset: 9500,
        cri_rate: 1510000,
        bit_rate: 1510000,
        cri_frc: 0,
        cri_frc_mask: 0,
        cri_bits: 0,
        frc_bits: 0,
        payload: 10 * 8,
        modulation: VbiModulation::NrzLsb,
        flags: VbiServiceParFlag::LineNum,
    },
];
